import { NextResponse, type NextRequest } from "next/server";

import {
  getChannelBreakdown,
  getDashboardStats,
  getDailySeries,
  getDepartmentBreakdown,
  getLevelBreakdown,
} from "@/lib/admin/analytics";
import { csvDocument, exportFilename } from "@/lib/admin/csv";
import { recordAudit } from "@/lib/audit/log";
import { requireAdminApi } from "@/lib/auth/guard";
import { prisma } from "@/lib/db/prisma";
import { minorToMajorString } from "@/lib/format/money";
import { toErrorResponse } from "@/lib/http/api";
import { clientIdentifier } from "@/lib/rate-limit/limiter";
import { cuidSchema } from "@/lib/validation/schemas";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GET /api/admin/reports/export
 *
 * The summary report as a single CSV: headline totals, then breakdowns by
 * level, department, channel and date. Generated entirely on the server.
 */
export async function GET(request: NextRequest) {
  try {
    const admin = await requireAdminApi("reports:read");

    const sessionParam = request.nextUrl.searchParams.get("sessionId");
    const parsedSession = sessionParam ? cuidSchema.safeParse(sessionParam) : null;

    const session = parsedSession?.success
      ? await prisma.academicSession.findUnique({ where: { id: parsedSession.data } })
      : await prisma.academicSession.findFirst({ where: { active: true } });

    const from = request.nextUrl.searchParams.get("from");
    const to = request.nextUrl.searchParams.get("to");
    const range = {
      from: from ? new Date(`${from}T00:00:00.000Z`) : undefined,
      to: to ? new Date(`${to}T23:59:59.999Z`) : undefined,
    };

    const [stats, levels, departments, channels, series] = await Promise.all([
      getDashboardStats(session?.id ?? null, range),
      getLevelBreakdown(session?.id ?? null),
      getDepartmentBreakdown(session?.id ?? null),
      getChannelBreakdown(session?.id ?? null),
      getDailySeries(session?.id ?? null, 30),
    ]);

    await recordAudit({
      action: "EXPORT_REPORT",
      entityType: "AcademicSession",
      entityId: session?.id ?? null,
      adminId: admin.id,
      adminEmail: admin.email,
      metadata: { export: "summary_csv", sessionName: session?.name ?? null, from, to },
      ip: clientIdentifier(request.headers),
    });

    const rows: unknown[][] = [
      ["COLBIOS Dues — summary report"],
      ["Academic session", session?.name ?? "All sessions"],
      ["Date range", `${from ?? "all time"} to ${to ?? "now"}`],
      ["Generated", new Date().toISOString()],
      ["Generated by", admin.email],
      [],
      ["Totals"],
      ["Total collected", minorToMajorString(stats.totalCollectedMinor), stats.currency],
      ["Total expected", minorToMajorString(stats.totalExpectedMinor), stats.currency],
      ["Paid students", stats.paidStudents],
      ["Outstanding students", stats.outstandingStudents],
      ["All transactions", stats.total],
      ["Successful", stats.byStatus.SUCCESS],
      ["Pending", stats.byStatus.PENDING],
      ["Failed", stats.byStatus.FAILED],
      ["Abandoned", stats.byStatus.ABANDONED],
      ["Refunded", stats.byStatus.REFUNDED],
      ["Reversed", stats.byStatus.REVERSED],
      [],
      ["By level", "Payments", "Collected"],
      ...levels.map((row) => [row.label, row.count, minorToMajorString(row.amountMinor)]),
      [],
      ["By department", "Payments", "Collected"],
      ...departments.map((row) => [row.label, row.count, minorToMajorString(row.amountMinor)]),
      [],
      ["By channel", "Payments", "Collected"],
      ...channels.map((row) => [row.label, row.count, minorToMajorString(row.amountMinor)]),
      [],
      ["By date (last 30 days)", "Payments", "Collected"],
      ...series.map((point) => [point.date, point.count, minorToMajorString(point.amountMinor)]),
    ];

    const csv = csvDocument([], rows).replace(/^\r\n/, "");

    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${exportFilename("colbios-summary")}"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    return toErrorResponse(error, "GET /api/admin/reports/export");
  }
}
