import Link from "next/link";

import { AdminCard, AdminPageHeader } from "@/components/admin/AdminShell";
import { BreakdownBars, StatTile } from "@/components/admin/Charts";
import {
  getChannelBreakdown,
  getDailySeries,
  getDashboardStats,
  getDepartmentBreakdown,
  getLevelBreakdown,
} from "@/lib/admin/analytics";
import { requireAdminPage } from "@/lib/auth/guard";
import { prisma } from "@/lib/db/prisma";
import { formatMoney } from "@/lib/format/money";

export const dynamic = "force-dynamic";

/**
 * Reporting.
 *
 * Every figure is computed server-side and only the aggregates reach the
 * browser — the page never ships a payment dataset for the client to total up.
 * Exports are generated by a server route with its own permission check.
 */
export default async function AdminReportsPage({
  searchParams,
}: {
  searchParams: Promise<{ sessionId?: string; from?: string; to?: string }>;
}) {
  await requireAdminPage("reports:read", "/admin/reports");
  const params = await searchParams;

  const sessions = await prisma.academicSession.findMany({
    orderBy: [{ active: "desc" }, { name: "desc" }],
    select: { id: true, name: true, active: true },
  });

  const selected =
    sessions.find((session) => session.id === params.sessionId) ??
    sessions.find((session) => session.active) ??
    sessions[0] ??
    null;

  const range = {
    from: params.from ? new Date(`${params.from}T00:00:00.000Z`) : undefined,
    to: params.to ? new Date(`${params.to}T23:59:59.999Z`) : undefined,
  };

  const [stats, levels, departments, channels, series] = await Promise.all([
    getDashboardStats(selected?.id ?? null, range),
    getLevelBreakdown(selected?.id ?? null),
    getDepartmentBreakdown(selected?.id ?? null),
    getChannelBreakdown(selected?.id ?? null),
    getDailySeries(selected?.id ?? null, 30),
  ]);

  const exportParams = new URLSearchParams();
  if (selected) exportParams.set("sessionId", selected.id);
  if (params.from) exportParams.set("from", params.from);
  if (params.to) exportParams.set("to", params.to);

  const busiestDay = [...series].sort((a, b) => b.amountMinor - a.amountMinor)[0];

  return (
    <>
      <AdminPageHeader
        title="Reports"
        description={selected ? `Figures for ${selected.name}.` : "No sessions configured yet."}
        actions={
          <>
            <a
              href={`/api/admin/payments/export?${exportParams.toString()}`}
              className="inline-flex min-h-[38px] items-center rounded-lg border border-line bg-white px-3 text-[13px] font-semibold text-ink hover:border-ink/30"
            >
              Export payments CSV
            </a>
            <a
              href={`/api/admin/reports/export?${exportParams.toString()}`}
              className="inline-flex min-h-[38px] items-center rounded-lg bg-pine-700 px-3 text-[13px] font-semibold text-white hover:bg-pine-800"
            >
              Export summary CSV
            </a>
          </>
        }
      />

      <AdminCard>
        <form method="get" className="flex flex-wrap items-end gap-3">
          <div className="w-52">
            <label htmlFor="sessionId" className="mb-1 block text-[12px] font-semibold text-muted">
              Session
            </label>
            <select
              id="sessionId"
              name="sessionId"
              defaultValue={selected?.id ?? ""}
              className="min-h-[42px] w-full rounded-lg border border-line bg-white px-3 text-[14px] text-ink outline-none focus:border-pine-600"
            >
              {sessions.map((session) => (
                <option key={session.id} value={session.id}>
                  {session.name}
                </option>
              ))}
            </select>
          </div>

          <div className="w-44">
            <label htmlFor="from" className="mb-1 block text-[12px] font-semibold text-muted">
              From
            </label>
            <input
              id="from"
              name="from"
              type="date"
              defaultValue={params.from ?? ""}
              className="min-h-[42px] w-full rounded-lg border border-line bg-white px-3 text-[14px] text-ink outline-none focus:border-pine-600"
            />
          </div>

          <div className="w-44">
            <label htmlFor="to" className="mb-1 block text-[12px] font-semibold text-muted">
              To
            </label>
            <input
              id="to"
              name="to"
              type="date"
              defaultValue={params.to ?? ""}
              className="min-h-[42px] w-full rounded-lg border border-line bg-white px-3 text-[14px] text-ink outline-none focus:border-pine-600"
            />
          </div>

          <button
            type="submit"
            className="inline-flex min-h-[42px] items-center rounded-lg bg-pine-700 px-4 text-[13.5px] font-semibold text-white hover:bg-pine-800"
          >
            Apply
          </button>
          <Link
            href="/admin/reports"
            className="inline-flex min-h-[42px] items-center rounded-lg border border-line px-4 text-[13.5px] font-semibold text-ink hover:border-ink/30"
          >
            Reset
          </Link>
        </form>
      </AdminCard>

      <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile
          label="Total collected"
          value={formatMoney(stats.totalCollectedMinor)}
          tone="positive"
        />
        <StatTile label="Total expected" value={formatMoney(stats.totalExpectedMinor)} />
        <StatTile label="Successful transactions" value={String(stats.byStatus.SUCCESS)} />
        <StatTile label="Pending transactions" value={String(stats.byStatus.PENDING)} />
        <StatTile label="Failed transactions" value={String(stats.byStatus.FAILED)} />
        <StatTile label="Abandoned checkouts" value={String(stats.byStatus.ABANDONED)} />
        <StatTile label="Refunds" value={String(stats.byStatus.REFUNDED)} />
        <StatTile label="Reversals" value={String(stats.byStatus.REVERSED)} />
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <AdminCard title="Payments by level">
          <BreakdownBars rows={levels} />
        </AdminCard>
        <AdminCard title="Payments by department">
          <BreakdownBars rows={departments} />
        </AdminCard>
        <AdminCard title="Payments by channel">
          <BreakdownBars rows={channels} />
        </AdminCard>
        <AdminCard title="Payments by date" description="Last 30 days, verified payments">
          <div className="-mx-5 max-h-[320px] overflow-y-auto px-5">
            <table className="w-full border-collapse text-left">
              <thead className="sticky top-0 bg-white">
                <tr className="border-b border-line text-[11.5px] uppercase tracking-wide text-muted">
                  <th scope="col" className="py-2 font-semibold">Date</th>
                  <th scope="col" className="py-2 font-semibold">Payments</th>
                  <th scope="col" className="py-2 text-right font-semibold">Collected</th>
                </tr>
              </thead>
              <tbody>
                {series
                  .filter((point) => point.count > 0)
                  .reverse()
                  .map((point) => (
                    <tr key={point.date} className="border-b border-line/60 last:border-0">
                      <td className="py-2 text-[13px] text-ink">{point.date}</td>
                      <td className="py-2 text-[13px] tabular-nums text-muted">{point.count}</td>
                      <td className="py-2 text-right text-[13px] font-semibold tabular-nums text-ink">
                        {formatMoney(point.amountMinor)}
                      </td>
                    </tr>
                  ))}
                {series.every((point) => point.count === 0) ? (
                  <tr>
                    <td colSpan={3} className="py-6 text-center text-[13px] text-muted">
                      No verified payments in the last 30 days.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
          {busiestDay && busiestDay.amountMinor > 0 ? (
            <p className="mt-3 text-[12px] text-muted">
              Busiest day: {busiestDay.date} · {formatMoney(busiestDay.amountMinor)}
            </p>
          ) : null}
        </AdminCard>
      </div>
    </>
  );
}
